version: "3"
services:
  dispatcher:
    image: mierzwid/httpd4dispatcher:0.0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - docker-net
    volumes:
      - "./build/distributions/mod_dispatcher.so:/etc/httpd/modules/mod_dispatcher.so"
      - "./build/cache:/opt/aem/dispatcher/cache"
      - "./build/logs:/var/log/httpd"
      - "./dispatcher/conf:/etc/httpd/conf"
networks:
  docker-net:
